:concurrency: 5
:queues:
  - receivable_liquidation
  - default

:scheduler:
  :schedule:
    receivable_liquidation:
      cron: "0 0 * * *"
      class: ReceivableLiquidationJob
      queue: receivable_liquidation